version: '3.9'  # Optional: Specify version if needed, though recent versions deprecate it.

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"  # Host port 3000 mapped to container port 80 (Nginx)
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"  # Host port 8000 mapped to container port 8000 (FastAPI)
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trading_db
      - PYTHONPATH=/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trading_db
    ports:
      - "5433:5432"  # Host port 5433 mapped to container port 5432 (PostgreSQL)
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
